### ISSUE TITLE
Excel 2007+ 

### ISSUE THREAD

**Issue by przemekwa** [jsegarra1971/SejExcelExport#3]
Hej, Your solution is amazing. Fast as hell : ) I used on production enviroment - 10 files with 1 000 000 rows create very fast -  every day for 2 years : ) Good job.

BUT

But I have error when I create temple file with excel 2010. It because that xml excel 2010 file is different. Some file is in other places. I want to repair this and remove the fact to have template file.

And I have a question  - Where do You learn about the build of xml Excel file? Now i don't understood the stream string and other streams. Do You have some good source of information od this topic?

**Comment by mrjono1** [comment]
Thanks for the great feedback!
Finding sources was the hardest part, originally I found a similar project that did part of what I am doing which helped. Then a lot of it was by looking inside the xlsx file while making changes in Excel to see what is going on. If you change .xlsx to .zip you can explore the underneath XML files. I think I also found a little help from a openxml website I'll see if I can find it
I know your pain I corrupted the files many times building this.

It is possible to make FastExcel also create an Excel file without a template

**Comment by jsegarra1971** [comment]
Thanks !! 

I developed it out of necessity as I needed, for an ETL, to generate excel files with millions of rows in a timely manner. So speed and low memory consumption were major considerations.  I used Excel 2010 during the development, so it works well with Excel 2010 files (.xlsx extension)

The Excel 2010 format is exactly the same as Excel 2007. It is a format based on Office Open XML. Make sure that your template is saved as "Excel workbook" (with extension.xlsx). Templates in previous versions (with extension ".xls") will not work.

What kind of errors are you getting ?

In my implementation I am indexing columns using a single CHAR, this means that you might get errors if your template has columns beyond 'Z'. This is an easy fix.

About your other question, the OOXML is an open specification, the Wikipedia link (https://en.wikipedia.org/wiki/Office_Open_XML will direct you to full specifications, samples and libraries. However, I just unzipped some sample XLSX files and inspected them as this was easier than reading the full specs.

Let me know if I can provide further help.

**Comment by przemekwa** [comment]
Ok, today I found what is happen. 

I change Your solution to  resolve mapping like this.


```
 private void GetMapping()
        {
            string[] cells;                                                         // Cells of current row
            int i = 0;                                                              // First row to review
            do                                                                      // Loop all the rows
            {
                cells = sheet.Row(i);                                               // Get cells for row [i]. WARNING template cannot be a BIG file. It's parsed fully in memory    
                if (cells != null) CheckMapping(i, cells);                          // If there are cells, check if they define a mapping
                i++;                                                                // Next row
            } while (cells != null && mapping.Count == 0);                          // Exit when there are no rows or a mapping has been found 


            if (mapping.Count == 0) // instead of rely on user columns name iI used only columns in DataTable source
            {
                for (int j = 0; j < data.ReportData.Columns.Count; j++)
                {
                    mapping.Add(j,j.ToString());
                }
            }
        }
```

And 
```
  for (int i = 0; i < mapping.Count; i++)
            {
                sheet.WriteCell(i, data[i]);
            }
```
instead of this:

```
  foreach(KeyValuePair<int,string> m in mapping)                          // For each mapping value
                sheet.WriteCell(m.Key, data[m.Value]);        
```

This change allow me to create  template like empy excel file. No need to create fields with text like "*Column1" "*Column2" 

But when I create empty excel file - file SharedStrings.xml don't create in excel xml hierarchy so this code


  if (s.zfe.FilenameInZip == "xl/_rels/workbook.xml.rels") rd = s.ReadAsXml();                                    //      Stream for Relations
                if (s.zfe.FilenameInZip == "xl/workbook.xml") sd = s.ReadAsXml();                                               //      Stream for structure
                if (s.zfe.FilenameInZip == "xl/sharedStrings.xml") st = s.ReadAsXml();                                          //      Stream for strings 
            }
            if ((rd == null) || (sd == null) || (st == null)) throw new Exception("Bad WorkBook");  

throw error because st was null.

Thanks to You now I understood much more so I will keep changing Your solusion to be more user friendly (generaly I want to create ONE dll wtih simple ExcelReader ane ExcelWriter methods and add some unit tests) 

 Thanks for answer.

**Comment by jsegarra1971** [comment]
Glad to know it is solved !!!

Thanks for the input.
