### ISSUE TITLE
Partial buffer writing NOT implemented

### ISSUE THREAD

**Issue by wind39** [jsegarra1971/SejExcelExport#4]
I've came across this message:

https://github.com/jsegarra1971/SejExcelExport/blob/master/MyExcelExport/OoXmlDataStream.cs#L111

I don't understand why. Can you please explain which situations might require partial buffer writing?

Thank you!

**Comment by jsegarra1971** [comment]
Hi,

A XLSX file is a bunch of XML files (some of these XML files have data [ie: data sheets] others not [ie: style info]) compressed into a ZIP file. The XLSX Writer:

- takes an XLSX input template and loads its XML streams (as OoXmlDataStreams) in memory
- using ZipStorer, by Jaime Olivares, writes the OoXmlDataStreams into a ZIP file. Non-data OoXmlDataStreams are copied "as-is". Data OoXmlDataStreams are expanded in "data-items" and written into the ZIP. "data items" are the blocks of the data sheet (XML row-begin marker, XML cell-begin marker, XML cell-content, XML cell-end marker, XML row-end marker) and are generated dynamically using the IDataReader.

For writing into the ZIP file, the ZipStorer.Store method uses a  buffer (byte[] buffer = new byte[16384]) to store & compress data before writing it to the output file. 

For non-data OoXmlDataStreams the 16K chunk size is only relevant for performance ( small chunks require more cycles and less memory pressure, and big chunks the opposite)

For data OoXmlDataStreams, the OoXmlDataStream.Read method writes a "data item" into the ZipStorer buffer. 

Now about your question: if the generated "data-item" does not fit in the 16K buffer, the exception will raise. "Data-items" are:

- cell contents, which are numbers and are always going to fit in a 16K buffer
- static data-markers (see MyExcelExport.Column), like row and value markers. Definitely fit in 16K
- cell attributes markers (see MyExcelExport.Column) generated from the template. It's unknown if they fit in 16K. 

So the exception will raise if the XML "chunk" expressing the attributes for cell exceeds the 16K limit. This seems rather unlikely, however I do not know the specification enough to completely rule out this possibility (embedding images??), that's the reason for the exception. 

If you ever encounter this exception, there are three solutions:
- the less complex: increase the buffer size, to fit your template
- use a dynamic buffer in the ZipStorer class and set its size to the biggest size of the columns objects for each datasheet (this involves modifying the ZipStorer component which isn't mine)
- use a more sofistified "data-item" schema for flow-control (ie: XML data-attribute-chunk or similar) and make sure a "data-item" always fits in the buffer.

Cell strings are not affected by this mechanism, the StringSheet is built dynamically and written to the ZIP as a single memory block (OoXmlStringsStream.Initialize).

**Comment by wind39** [comment]
Hi Jose,

Thank you so much for your detailed explanation!

Now I'll explain to you some details about the problem I've came across. This is the exception I've found:

    System.Exception: Partial buffer writing NOT implemented
    at SejExcel.OoXmlDataStream.WriteBytes (System.Byte[] w, System.Byte[] buffer, Int32 pos) <0x40b552b0 + 0x00127> in :0 
    at SejExcel.OoXmlDataStream.Read (System.Byte[] buffer, Int32 start, Int32 count) <0x40b55180 + 0x0003f> in :0 
    at ZipStorer.Store (Spartacus.ThirdParty.ZipFileEntry& _zfe, System.IO.Stream _source) <0x40b54480 + 0x0011b> in :0 
    at ZipStorer.AddStream (Compression _method, System.String _filenameInZip, System.IO.Stream _source, DateTime _modTime, System.String _comment) <0x40b53be0 + 0x002ab> in :0 
    at SejExcel.OoXml.Save (System.String file_name) <0x40b53650 + 0x00123> in :0 

By the time, I thought I NEEDED to implement partial buffer, and then I tried with the following piece of code:

    private int WriteBytes(byte[] w, byte[] buffer,int pos)
    {
        /* Jose Segarra's
        int j = w.Length;
        if (buffer.Length < j) throw new Exception("Partial buffer writing NOT implemented");
        System.Buffer.BlockCopy(w, 0, buffer, pos, j);
        return j;
        */

        // William Ivanski's
        int r = w.Length;
        int p1 = 0;
        int p2 = pos;
        if (p2 >= buffer.Length)
            p2 = 0;
        int s = 0;
        while (r > 0)
        {
            if (r > (buffer.Length - p2))
                s = buffer.Length - p2;
            else
                s = r;

            System.Buffer.BlockCopy(w, p1, buffer, p2, s);

            r -= s;
            p1 += s;
            p2 += s;
            if (p2 >= buffer.Length)
                p2 = 0;
        }
        return p2;
    }

But it didn't work. After my alteration, it raised exceptions on different moments. That's when I gave up and opened this issue to ask you.

Now I understand the problem probably resides within the template I'm using. So, I doubled the size of the ZipStorer buffer (32768), as you suggested, and now it's working.

Thanks again for your help!
